### ISSUE TITLE
✅ To-do

### ISSUE THREAD

**Issue by alexmercerind** [alexmercerind/harmonoid#28]
**Following features & bug-fixes are planned in future releases.**

- [ ] Compiling for Windows 10.
- [ ] Compiling for Windows 10.
- [ ] Compiling for Windows 10.
- [ ] Compiling for Windows 10.
- [ ] Compiling for Windows 10.
- [ ] Compiling for Windows 10.
